# Generated by Django 4.1 on 2023-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Emp_id", models.IntegerField()),
                ("Emp_name", models.CharField(max_length=50)),
                ("Emp_DOB", models.DateField()),
            ],
        ),
    ]
